---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# sonatype-lifecycle-scan-action
name: '🔐 Sonatype Lifecycle Scan'
description: 'Runs a Sonatype Lifecycle (Nexus IQ) scan'

inputs:
  # Note: types are not enforced for composite actions and fail schema checks
  # But are useful for documentation purposes and will be commented out

  # Mandatory
  nexus_iq_server:
    description: 'Nexus IQ Server URL'
    required: true
    # type: string
  nexus_iq_username:
    description: 'Nexus IQ Username'
    required: true
    # type: string
  nexus_iq_password:
    description: 'Nexus IQ Password'
    required: true
    # type: string

  # Optional
  no_checkout:
    description: 'Do not checkout local repository; used for testing'
    required: false
    default: 'false'
    # type: boolean
  java_distribution:
    description: 'JAVA SE distribution to setup/run for Nexus CLI tool'
    required: false
    default: 'temurin'
    # type: string
  java_version:
    description: 'Java runtime to setup/run for Nexus CLI tool'
    required: false
    default: '17'
    # type: number
  iq_cli_version:
    description: 'Specific version of Nexus CLI to setup/run'
    required: false
    # default: '2.4.2-01'
    default: 'latest'
    # type: string
  application_id:
    description: 'Organisation and project name in Nexus IQ'
    required: false
    # yamllint disable-line rule:line-length
    default: "${{ github.repository_owner }}-${{ github.event.repository.name }}"
    # type: string
  scan_targets:
    description: 'Location of file(s) or folder(s) to scan'
    required: false
    default: '.'
    # type: string
  debug:
    description: 'Enable debugging output'
    required: false
    default: 'false'
    # type: boolean

runs:
  using: 'composite'
  steps:
    - name: 'Check action inputs/environment'
      shell: bash
      run: |
        # Check action inputs/environment
        echo "Java Distribution: ${{ inputs.java_distribution }}"
        echo "Java Version: ${{ inputs.java_version }}"
        echo "IQ CLI Version: ${{ inputs.iq_cli_version }}"
        echo "Application ID: ${{ inputs.application_id }}"
        echo "Scan Targets: ${{ inputs.scan_targets }}"
        echo "Debug Mode: ${{ inputs.debug }}"

        echo "Verifying mandatory inputs 💬"
        # Check mandatory parameters
        if [ -n "${{ inputs.nexus_iq_server }}" ]; then
          echo "Nexus IQ Server: ${{ inputs.nexus_iq_server }}"
        else
          echo "Nexus IQ Server not provided as input"
          error='true'
        fi
        if [ -n "${{ inputs.nexus_iq_username }}" ]; then
          echo "Nexus IQ Username: ${{ inputs.nexus_iq_username }}"
        else
          echo "Nexus IQ Username not provided as input"
          error='true'
        fi
        if [ -n "${{ inputs.nexus_iq_password }}" ]; then
          echo "Nexus IQ Password: [REDACTED]"
        else
          echo "Nexus IQ Password not provided as input"
          error='true'
        fi
        if [ "$error" = 'true' ]; then
          echo "Error: one or more mandatory inputs are missing"
          echo "Check variables/secrets are set in Org/repository"
          echo "Provide all required inputs to the action ❌"
          exit 1
        else
          echo "All mandatory inputs provided ✅"
        fi

    - name: 'Setup Sonatype CLI'
      # yamllint disable-line rule:line-length
      uses: sonatype/actions/setup-iq-cli@6b5a197467c9b34ba91c17bd0f1aa6077afb19fe # v.1.6.2
      with:
        iq-cli-version: ${{ inputs.iq_cli_version }}

    # Sonatype CLI requires Java to run
    - name: 'Setup Java'
      # yamllint disable-line rule:line-length
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}

    - name: 'Checkout repository'
      # yamllint disable-line rule:line-length
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      if: inputs.no_checkout != 'true'

    - name: 'Debug action/environment'
      if: inputs.debug == 'true'
      shell: bash
      run: |
        # Show local directory context
        echo "Debug logging enabled 🐞"
        echo "Current directory: $(pwd)"
        echo "GitHub workspace: ${{ github.workspace }}"
        echo "Directory content:"
        ls -la

    - name: 'Run Sonatype CLI'
      # yamllint disable-line rule:line-length
      uses: sonatype/actions/run-iq-cli@6b5a197467c9b34ba91c17bd0f1aa6077afb19fe # v1.6.2
      with:
        iq-server-url: ${{ inputs.nexus_iq_server }}
        username: ${{ inputs.nexus_iq_username }}
        password: ${{ inputs.nexus_iq_password }}
        application-id: ${{ inputs.application_id }}
        scan-targets: ${{ inputs.scan_targets }}
        debug: ${{ inputs.debug }}
